version: "3.7"

services:

  reverseproxy:
    build:
      context: ./Nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  api1:
    depends_on:
      - reverseproxy
    build:
      context: ./HelloAspNetCore6.Api
      dockerfile: Api.Dockerfile
    expose:
      - "5000"
    restart: always
 
  api2:
    depends_on:
        - reverseproxy
    build:
        context: ./HelloAspNetCore6.Api
        dockerfile: Api.Dockerfile
    expose:
        - "5000"
    restart: always

# docker-compose build
# docker-compose up -d
# docker-compose down

# Browse to: http://localhost/weatherforecast
